const CREATE_OFFICE = 'CREATE_OFFICE';
const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE_SUCCESS';
const CREATE_OFFICE_ERROR = 'CREATE_OFFICE_ERROR';

const REMOVE_OFFICE = 'REMOVE_OFFICE';
const REMOVE_OFFICE_SUCCESS = 'REMOVE_OFFICE_SUCCESS';
const REMOVE_OFFICE_ERROR = 'REMOVE_OFFICE_ERROR';

const UPDATE_OFFICE = 'UPDATE_OFFICE';
const DELETE_OFFICE = 'DELETE_OFFICE';
const TOGGLE_OFFICE_EDITABLE = 'TOGGLE_OFFICE_EDITABLE';

const GET_OFFICES = 'GET_OFFICES';
const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';
const GET_OFFICES_ERROR = 'GET_OFFICES_ERROR';

export default {
  CREATE_OFFICE,
  CREATE_OFFICE_SUCCESS,
  CREATE_OFFICE_ERROR,
  REMOVE_OFFICE,
  REMOVE_OFFICE_SUCCESS,
  REMOVE_OFFICE_ERROR,
  UPDATE_OFFICE,
  DELETE_OFFICE,
  TOGGLE_OFFICE_EDITABLE,
  GET_OFFICES,
  GET_OFFICES_SUCCESS,
  GET_OFFICES_ERROR
}
