const CREATE_OFFICE = 'CREATE_OFFICE';
const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE_SUCCESS';
const CREATE_OFFICE_ERROR = 'CREATE_OFFICE_ERROR';

const TOGGLE_NEW_OFFICE_FORM = 'TOGGLE_NEW_OFFICE_FORM';
const TOGGLE_EDITABLE_OFFICE_FORM = 'TOGGLE_EDITABLE_OFFICE_FORM';

const REMOVE_OFFICE = 'REMOVE_OFFICE';
const REMOVE_OFFICE_SUCCESS = 'REMOVE_OFFICE_SUCCESS';
const REMOVE_OFFICE_ERROR = 'REMOVE_OFFICE_ERROR';

const UPDATE_OFFICE = 'UPDATE_OFFICE';
const UPDATE_OFFICE_SUCCESS = 'UPDATE_OFFICE_SUCCESS';
const UPDATE_OFFICE_ERROR = 'UPDATE_OFFICE_ERROR';

const GET_OFFICES = 'GET_OFFICES';
const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';
const GET_OFFICES_ERROR = 'GET_OFFICES_ERROR';

export default {
  CREATE_OFFICE,
  CREATE_OFFICE_SUCCESS,
  CREATE_OFFICE_ERROR,
  REMOVE_OFFICE,
  REMOVE_OFFICE_SUCCESS,
  REMOVE_OFFICE_ERROR,
  UPDATE_OFFICE,
  UPDATE_OFFICE_SUCCESS,
  UPDATE_OFFICE_ERROR,
  GET_OFFICES,
  GET_OFFICES_SUCCESS,
  GET_OFFICES_ERROR,
  TOGGLE_NEW_OFFICE_FORM,
  TOGGLE_EDITABLE_OFFICE_FORM
}
